name: ai-call-center
services:
- name: backend
  source_dir: services
  github:
    repo: Nyvio-AI/ai-call-center
    branch: main
  run_command: uvicorn api.bootstrap:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: PLIVO_AUTH_ID
    scope: RUN_TIME
    type: SECRET
  - key: PLIVO_AUTH_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET

- name: frontend
  source_dir: app
  github:
    repo: Nyvio-AI/ai-call-center
    branch: main
  build_command: npm install && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs

databases:
- name: db
  engine: PG
  version: "13"
